pipeline {
    environment {
        docker_registry = "lucasdelimanogueira/generic-scalable-ai-system"
        dockerhub_credential_id = "dockerhub-credential"
    }

    agent any

    stages {
        stage ('Build Image') {
            steps {
                script {
                    dockerapp = docker.build(docker_registry + ":${env.BUILD_ID}", "-f ./model-server/Dockerfile ./model-server")
                }
            }
        }

        stage ('Test Image') {
            steps {
                script {
                    // run the container
                    sh "docker run --shm-size 1g --net=host -v ${PWD}/model_repository:/models $docker_registry:$BUILD_ID &"
                    
                    // check if the triton server service started correctly  
                    def maxRetries = 2  
                    def retryInterval = 10  
                    def retries = 0
                    def serviceReady = false
                    
                    sleep retryInterval

                    while (!serviceReady && retries < maxRetries) {
                        def curlOutput = sh(script: "curl -s -o /dev/null -w \"%{http_code}\" localhost:8000/v2/health/ready", returnStdout: true, returnStatus: true)
                        if (curlOutput == "200") {
                            echo "Service is ready!"
                            serviceReady = true
                        } else {
                            echo "Service is not yet ready, waiting for $retryInterval seconds before retrying..."
                            sleep retryInterval
                            retries++
                        }
                    }

                    if (!serviceReady) {
                        echo "Service did not become ready within the specified timeout"
                        sh "docker stop $docker_registry:${env.BUILD_ID}"
                        sh "docker rmi $docker_registry:$BUILD_ID"
                    }
                }
            }
        }

        /*stage ('Push Image') {
            steps {
                script {
                    docker.withRegistry("https://registry.hub.docker.com", dockerhub_credential_id)
                    dockerapp.push("latest")
                    dockerapp.push("${env.BUILD_ID}")

                    sh "docker rmi $docker_registry:$BUILD_ID"
                }
            }
        }*/
    }
}