pipeline {
    agent any

    stages {
        stage ('Build Image') {
            steps {
                script {
                    docker = docker.build("lucasdelimanogueira/generic-scalable-ai-system", "-f model-server/Dockerfile")
                }
            }
        }
    }
}